#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

token=$(ynh_string_random --length=45 | base64)
ynh_app_setting_set --key=token --value=$token

secret=$(ynh_string_random --length=45 | base64)
ynh_app_setting_set --key=secret --value=$secret

#=================================================
# INSTALL PYTHON DEPENDENCIES
#=================================================
ynh_script_progression "Installing Python dependencies..."

pushd $install_dir
    python3 -m venv $install_dir/venv
    ynh_hide_warnings $install_dir/venv/bin/pip install "argos-monitoring[gunicorn,ldap]"
popd

chown -R $app:$app "$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="argos-config.yaml" --destination="$install_dir/config.yaml"
chmod 600 "$install_dir/config.yaml"
chown "$app:$app" "$install_dir/config.yaml"

ynh_config_add --template="argos-server" --destination="$install_dir/argos-server"
chmod 600 "$install_dir/argos-server"
chown "$app:$app" "$install_dir/argos-server"

ynh_config_add --template="argos-agent" --destination="$install_dir/argos-agent"
chmod 600 "$install_dir/argos-agent"
chown "$app:$app" "$install_dir/argos-agent"


#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd --service="argos-server" --template="argos-server.service"
ynh_config_add_systemd --service="argos-agent" --template="argos-agent.service"

yunohost service add "argos-server" --description="Monitoring and status board for your websites" --log="/var/log/$app/$app.log"
yunohost service add "argos-agent" --description="Monitoring and status board for your websites" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

#=================================================
# ADD A CRON JOB
#=================================================

ynh_config_add --template="cron" --destination="/etc/cron.d/$app"
chown root: "/etc/cron.d/$app"
chmod 644 "/etc/cron.d/$app"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="argos-server" --action="start"
ynh_systemctl --service="argos-agent" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
