#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

if ynh_hide_warnings yunohost service status "argos-server" >/dev/null; then
    yunohost service remove "argos-server"
fi

if ynh_hide_warnings yunohost service status "argos-agent" >/dev/null; then
    yunohost service remove "argos-agent"
fi

ynh_config_remove_systemd "argos-server"
ynh_config_remove_systemd "argos-agent"

ynh_config_remove_nginx

ynh_safe_rm "/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
