#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

if ynh_hide_warnings yunohost service status "argo-server" >/dev/null; then
    yunohost service remove "argo-server"
fi

if ynh_hide_warnings yunohost service status "argo-agent" >/dev/null; then
    yunohost service remove "argo-agent"
fi

ynh_config_remove_systemd "argo-server"
ynh_config_remove_systemd "argo-agent"

ynh_config_remove_nginx

ynh_safe_rm "/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
